# Generated by Django on 2025-10-11
from django.db import migrations, models
from django.db.models import F


def forwards(apps, schema_editor):
    NewsItem = apps.get_model('website', 'NewsItem')
    # Backfill: if event_start is null and date_event not null, copy date_event -> event_start
    NewsItem.objects.filter(event_start__isnull=True, date_event__isnull=False).update(event_start=F('date_event'))


def backwards(apps, schema_editor):
    # No-op: keep data as-is
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True, help_text="Début de l'événement (date & heure)"),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True, help_text="Fin de l'événement (date & heure)"),
        ),
        migrations.RunPython(forwards, backwards),
    ]
