# Generated by Django on 2025-10-12 00:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactmessage_extra_fields'),
        ('website', '0002_newsitem_event_range'),
    ]

    operations = [
        # Merge migration: no-op
    ]
