# Generated by Django 5.0.6 on 2025-10-12 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_merge_20251012_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('file', 'Fichier')], default='file', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 en premier)")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='website.newsitem')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ('order', 'id'),
            },
        ),
    ]
