# Generated by Django 5.0.6 on 2025-10-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_newsmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
