# Generated by Django 5.0.6 on 2025-10-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeunes_formes', models.CharField(default='120+', max_length=50, verbose_name='Jeunes formés')),
                ('sessions_sante', models.CharField(default='35', max_length=50, verbose_name='Sessions santé')),
                ('actions_environnement', models.CharField(default='18', max_length=50, verbose_name='Actions environnement')),
            ],
            options={
                'verbose_name': "Métriques d'impact",
                'verbose_name_plural': "Métriques d'impact",
            },
        ),
    ]
