# Generated by Django 5.0.6 on 2025-10-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_impactmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmetrics',
            name='zones_intervention',
            field=models.CharField(default='5', max_length=50, verbose_name="Zones d'intervention"),
        ),
    ]
