# Generated by Django 5.0.6 on 2025-11-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_impactmetrics_zones_intervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la collection')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('source_folder', models.CharField(help_text='Sous-dossier de media/gallery_sources/ contenant images et vidéos', max_length=255, verbose_name='Sous-dossier source')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
            },
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Centre', 'verbose_name_plural': 'Centres'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ('-created',), 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='website.gallerycollection')),
            ],
            options={
                'verbose_name': 'Média de galerie',
                'verbose_name_plural': 'Médias de galerie',
                'ordering': ('id',),
            },
        ),
    ]
