# Generated by Django 5.0.6 on 2025-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_gallerycollection_alter_center_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycollection',
            name='source_folder',
            field=models.CharField(blank=True, help_text='(Optionnel) Sous-dossier de media/gallery_sources/ contenant images et vidéos', max_length=255, verbose_name='Sous-dossier source'),
        ),
    ]
